export const keyChatBot = {
    STEP_0: "STEP_0",
    STEP_1: "STEP_1",
    DEFAULT: "DEFAULT",
    PRODUCTS: "PRODUCTS",
    SEARCH: "SEARCH",
    NOT_FONT: "NOT_FONT",
    ADMIN: "ADMIN",
    KEY: "1234",
    CREATE: "CREATE",
    UPDATE: "UPDATE",
    DELETE: "DELETE",
    ADD_CATEGORY: "ADD_CATEGORY",
    ADD_DESCRIPTION: "ADD_DESCRIPTION",
    ADD_SIZE_PRICE: "ADD_SIZE_PRICE",
    FINALLY_SAVE: "ADD_SIZE_PRICE",
    ERROR_SAVE: "ERROR_SAVE"
}